// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxgugjdhaxbyvhtfokrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4Z3VnamRoYXhieXZodGZva3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDY2NzgsImV4cCI6MjA2NTU4MjY3OH0.t6N33OLEBOvH8SfgoPDupS8G1bpbvUISjJLfjhgY9mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);