# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "TriChat Live Chat"
client_id = "YOUR_CLIENT_ID"
application_url = "https://your-app-domain.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_inventory,write_inventory,read_script_tags,write_script_tags,read_themes,write_themes,read_analytics,read_marketing_events,write_marketing_events,read_price_rules,write_price_rules,read_discounts,write_discounts,read_marketing_events,write_marketing_events,read_shopify_payments_payouts,read_shopify_payments_disputes,read_locales,write_locales,read_fulfillments,write_fulfillments,read_shipping,write_shipping,read_returns,write_returns,read_gift_cards,write_gift_cards,read_users,write_users,read_checkouts,write_checkouts,read_reports,write_reports,read_price_rules,write_price_rules,read_discounts,write_discounts,read_marketing_events,write_marketing_events,read_shopify_payments_payouts,read_shopify_payments_disputes,read_locales,write_locales,read_fulfillments,write_fulfillments,read_shipping,write_shipping,read_returns,write_returns,read_gift_cards,write_gift_cards,read_users,write_users,read_checkouts,write_checkouts,read_reports,write_reports"

[auth]
redirect_urls = [
  "https://your-app-domain.com/auth/callback",
  "https://your-app-domain.com/auth/shopify/callback",
  "https://your-app-domain.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"
include_config_on_deploy = true

[app_preview]
url = "https://your-app-domain.com/preview" 